module.exports.categoryController = require('./category.controller')
module.exports.courseController = require('./course.controller')
module.exports.userController = require('./user.controller')
module.exports.TermsController = require('./terms.controller')
module.exports.demoController = require('./demo.controller')
module.exports.sectionController = require('./section.controller')